spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/vdt-e-store?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true

websiteUrl: http://localhost:5173